export default {
  CAT_TREE: require('../assets/animations/cat_tree.json'),
  LOVE_SOCKS: require('../assets/animations/love_socks.json'),
  BALL_BALLS: require('../assets/animations/ball_ball_down.json'),
  HOT_COCO: require('../assets/animations/hot_coco.json'),
  BIRD: require('../assets/animations/bird.json'),
  POKING_CAT: require('../assets/animations/poking_cat.json'),
  CAT_JUMPING: require('../assets/animations/cat_jumping.json'),
  CHRISTMAS_TREE: require('../assets/animations/chirstmas_tree.json'),
  CHRISTMAS_BELL: require('../assets/animations/christmas_bell.json'),
  CHRISTMAS_EXPLOSION: require('../assets/animations/christmas_explosion.json'),
  CHRISTMAS_PUDDING_LOADER: require('../assets/animations/christmas_pudding_loader.json'),
  CHRISTMAS_SOCK: require('../assets/animations/christmas_sock.json'),
  CHRISTMAS_PRESENT: require('../assets/animations/jumping_present.json'),
  WEIRD_SANTA: require('../assets/animations/weird_santa.json'),
  WHITE_CHRISTMAS_TREE: require('../assets/animations/white_christmas_tree.json'),
  CONFETTI: require('../assets/animations/confetti.json'),
};
