import { svgs } from '../themes';

export const AdventSvgs = [
  svgs.ADVENT_CAT_1,
  svgs.ADVENT_CAT_2,
  svgs.ADVENT_CAT_3,
  svgs.ADVENT_CAT_4,
  svgs.ADVENT_CAT_5,
  svgs.ADVENT_CAT_6,
  svgs.ADVENT_CAT_32,
  svgs.ADVENT_CAT_31,
  svgs.ADVENT_CAT_28,
  svgs.ADVENT_CAT_27,
  svgs.ADVENT_CAT_26,
  svgs.ADVENT_CAT_25,
  svgs.ADVENT_CAT_24,
  svgs.ADVENT_CAT_23,
  svgs.ADVENT_CAT_22,
  svgs.ADVENT_CAT_21,
  svgs.ADVENT_CAT_20,
  svgs.ADVENT_CAT_8,
  svgs.ADVENT_CAT_9,
  svgs.ADVENT_CAT_10,
  svgs.ADVENT_CAT_11,
  svgs.ADVENT_CAT_12,
  svgs.ADVENT_CAT_13,
  svgs.ADVENT_CAT_14,
];
