import { images, svgs } from '../themes';

export const AdventSvgs = [
  svgs.ADVENT_CAT_1,
  svgs.ADVENT_CAT_2,
  svgs.ADVENT_CAT_3,
  svgs.ADVENT_CAT_4,
  svgs.ADVENT_CAT_5,
  svgs.ADVENT_CAT_6,
  svgs.ADVENT_CAT_7,
  svgs.ADVENT_CAT_8,
  svgs.ADVENT_CAT_9,
  svgs.ADVENT_CAT_10,
  svgs.ADVENT_CAT_11,
  svgs.ADVENT_CAT_12,
  svgs.ADVENT_CAT_13,
  svgs.ADVENT_CAT_14,
  svgs.ADVENT_CAT_15,
  svgs.ADVENT_CAT_16,
  svgs.ADVENT_CAT_1,
  svgs.ADVENT_CAT_2,
  svgs.ADVENT_CAT_8,
  svgs.ADVENT_CAT_9,
  svgs.ADVENT_CAT_10,
  svgs.ADVENT_CAT_11,
  svgs.ADVENT_CAT_12,
  svgs.ADVENT_CAT_13,
  svgs.ADVENT_CAT_14,
];

export const AdventImages = [
  images.ADVENT_CAT_1,
  images.ADVENT_CAT_2,
  images.ADVENT_CAT_3,
  images.ADVENT_CAT_4,
  images.ADVENT_CAT_5,
  images.ADVENT_CAT_6,
  images.ADVENT_CAT_7,
  images.ADVENT_CAT_8,
  images.ADVENT_CAT_9,
  images.ADVENT_CAT_10,
  images.ADVENT_CAT_11,
  images.ADVENT_CAT_12,
  images.ADVENT_CAT_13,
  images.ADVENT_CAT_14,
  images.ADVENT_CAT_15,
  images.ADVENT_CAT_16,
  images.ADVENT_CAT_1,
  images.ADVENT_CAT_2,
  images.ADVENT_CAT_8,
  images.ADVENT_CAT_9,
  images.ADVENT_CAT_10,
  images.ADVENT_CAT_11,
  images.ADVENT_CAT_12,
  images.ADVENT_CAT_13,
  images.ADVENT_CAT_14,
];
